# Learn more about services, parameters and containers at
# http://symfony.com/doc/current/book/service_container.html
#parameters:
#    parameter_name: value

services:
    app.file_entity_factory:
        class: AppBundle\Factory\FileEntityFactory
        arguments:
            - @doctrine.orm.entity_manager

    app.line_entity_factory:
        class: AppBundle\Factory\LineEntityFactory

    app.per_page_service:
        class: AppBundle\Service\PerPage
        arguments:
            - @session
            - @form.factory
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    app.twig_per_page_extension:
        class: AppBundle\Twig\PerPageExtension
        arguments:
            - @app.per_page_service
        public: false
        tags:
            - { name: twig.extension }

    app.apply_line_filter_factory:
        class: AppBundle\Filter\ApplyLineFilterFactory

    app.import_lock_factory:
        class: AppBundle\Service\ImportLockFactory
