<?php

namespace AppBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * LineRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LineRepository extends EntityRepository
{
    /**
     * @return Line
     */
    public function findLast()
    {
        return $this->createQueryBuilder('l')
            ->select()
            ->orderBy('l.createdAt', 'desc')
            ->getQuery()
            ->setMaxResults(1)
            ->getOneOrNullResult();
    }

}
